package com.csc.excel;

import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;

import com.dtec.reconcile.RC14Reconcile;
import com.dtec.reconcile.ReconcileDo;

public class JavaMain {
	public static void main(String...args) throws SQLException{
		ReconcileDo r=new ReconcileDo();
		Map<String,String>maps=new HashMap<>();
		//list of success RC01,RC02(SRNO.),RC03,RC04,RC06,RC07,RC08,RC09,RC11,RC12A,RC12B,RC15B,RC16,RC17,RC18,RC19
		//remain reconcile RC05,RC14
		//RC10 not use
		//maps.put("RC10","Select INPLANCODE,PAIDYYYYMM,POLYR,DSTGPREM,DTARPREM,DDIFPREM,DSTGPRMALLOC,DTARPRMALLOC,DDIFPRMALLOC,DSTGTOPUP,DTARTOPUP,DDIFTOPUP,DSTGTOPALLOC,DTARTOPALLOC,DDIFTOPALLOC,DSTGPOLFEE,DTARPOLFEE,DDIFPOLFEE,DSTGCOI,DTARCOI,DDIFCOI from RC10_TAR");
		maps.put("RC01","SELECT RC01.DPROCESSSEQ,RC01.STRRECLAREA,RC01.STRRECLITEM,RC01.STRRECLCRITERIA,RC01.DSTGRECLRESULT,NVL(RC01.DTARRECLRESULT,0),RC01.STRRECLSTS FROM VM1DTA.RC01_TAR RC01 ORDER BY DPROCESSSEQ");
		maps.put("RC02","SELECT '',rc02.STRCONTSTS,rc02.NSTGCONCNT,rc02.NTARCONCNT,rc02.NDIFFCONCNT,rc02.DSTGBPSAAMNT,rc02.DTARBPSAAMNT,rc02.DDIFFBPSAAMNT,rc02.DSTGRDSAAMNT,rc02.DTARRDSAAMNT,rc02.DDIFFRDSAAMNT,rc02.DSTGINSTPRM,rc02.DTARINSTPRM,rc02.DDIFFINSTPRM,rc02.DSTRTOTPRMRECV,rc02.DTARTOTPRMRECV,rc02.DDIFFTOTPRMRECV,rc02.DSTGSUSBALAMNT,rc02.DTARSUSBALAMNT,rc02.DDIFFSUSBALAMNT FROM VM1DTA.RC02_TAR rc02");
		maps.put("RC03","SELECT '',CRTABLE,'',COVTYPE,NSTGCONCNT,NTARCONCNT,NDIFFCONCNT,DSTGORISA,DTARORISA,DDIFFORISA,DSTGCURSA,DTARCURSA,DDIFFCURSA,DSTGREGPREM,DTARREGPREM,DDIFFREGPREM,DSTGSNGPREM,DTARSNGPREM,DDIFFSNGPREM,DSTGTOTPREM,DTARTOTPREM,DDIFFTOTPREM from rc03_TAR");
		maps.put("RC04","SELECT STRLEVEL, STRRISKSTS, STRPREMSTS, NSTGCONCNT, NTARCONCNT, NDIFFCONCNT, NSTGCASH, NTARCASH, NDIFFCASH, NSTGCHEQUE, NTARCHEQUE, NDIFCHEQUE, NSTGCCCNT, NTARCCCNT, NDIFFCCCNT, NSTGDDCNT, NTARDDCNT, NDIFFDDCNT, NSTGMNTBILL, NTARMNTBILL, NDIFFMNTBILL, NSTGQRTBILL, NTARQRTBILL, NDIFFQRTBILL, NSTGHYLBILL, NTARHYLBILL, NDIFFHYLBILL, NSTGYRLBILL, NTARYRLBILL, NDIFFYRLBILL, NSTGSNGBILL, NTARSNGBILL, NDIFFSNGBILL from RC04_TAR");
		maps.put("RC06","SELECT '',STRRCITEM,STRITEMDETAIL,NSTGLACOUNT,NTARLACOUNT,NDIFFLACOUNT,NSTGOWCOUNT,NTAROWCOUNT,NDIFFOWCOUNT,NSTGPYCOUNT,NTARPYCOUNT,NDIFFPYCOUNT,NSTGBNCOUNT,NTARBNCOUNT,NDIFFBNCOUNT,NSTGAGCOUNT,NTARAGCOUNT,NDIFFAGCOUNT,NSTGAGAGNTCNT,NTARAGAGNTCNT,NDIFAGAGNTCNT from RC06_TAR");
		maps.put("RC07","SELECT STRRISKSTS,VRTFND,STRFUNDNMT,STRFUNDNME,NSTGPOLCNT,NTARPOLCNT,NDIFFPOLCNT,DSTGTOTACVAL,DTARTOTACVAL,DDIFFTOTACVAL,DSTGGURACVAL,DTARGURACVAL,DDIFFGURACVAL,DSTGSURVAL,DTARSURVAL,DDIFFSURVAL,DSTGUNTONHOLD,DTARUNTONHOLD,DDIFFUNTONHOLD FROM RC07_TAR ORDER BY SRNO,STRRISKSTS,VRTFND");
		maps.put("RC08","SELECT STRBANKKEY,STRRISKSTS,STRPREMSTS,NSTGDDCONCNT,NTARDDCONCNT,NDIFFDDCONCNT,NSTGCCCONCNT,NTARCCCONCNT,NDIFFCCCONCNT,NSTGDDACCNT,NTARDDACCNT,NDIFFDDACCNT,NSTGCCACCNT,NTARCCACCNT,NDIFFCCACCNT FROM RC08_TAR rc8 WHERE rc8.nTARddconcnt > 0 Order by STRBANKKEY,STRRISKSTS,STRPREMSTS");
		maps.put("RC09","SELECT VRTFND,EFFDATE,NSTGCONCNT,NTARCONCNT,NDIFFCONCNT,DSTGDIVAMNT,DTARDIVAMNT,DDIFFDIVAMNT,DSTGFNDUNT,DTARFNDUNT,DDIFFFNDUNT,DSTGFUNDAMTN,DTARFUNDAMNT,DDIFFFUNDAMNT FROM RC09_TAR ORDER BY STRCRITERIA DESC,VRTFND,EFFDATE");
		maps.put("RC11","Select SRNO,STRREASONCD,STRREASONDESC,NSTGT643CNT,NTART643CNT,NDIFT643CNT,NSTGT644CNT,NTART644CNT,NDIFT644CNT,NSTGT645CNT,NTART645CNT,NDIFT645CNT,NSTGT668CNT,NTART668CNT,NDIFT668CNT,NSTGTA63CNT,NTARTA63CNT,NDIFTA63CNT,NSTGTR6VCNT,NTARTR6VCNT,NDIFTR6VCNT,NSTGTR7KCNT,NTARTR7KCNT,NDIFTR7KCNT,NSTGTOTALCNT,NTARTOTALCNT,NDIFTOTALCNT from RC11_TAR");
		maps.put("RC121","SELECT SRNO,FROMDATE,TODATE,NSTGUSP2WTHDAMNT,NTARUSP2WTHDAMNT,NDIFUSP2WTHDAMNT,NSTGUSP2FEEAMNT,NTARUSP2FEEAMNT,NDIFUSP2FEEAMNT,NSTGUSP2PENTAMNT,NTARUSP2PENTAMNT,NDIFUSP2PENTAMNT,NSTGUSP2CONTCNT,NTARUSP2CONTCNT,NDIFUSP2CONTCNT,NSTGUSP3WTHDAMNT,NTARUSP3WTHDAMNT,NDIFUSP3WTHDAMNT,NSTGUSP3FEEAMNT,NTARUSP3FEEAMNT,NDIFUSP3FEEAMNT,NSTGUSP3PENTAMNT,NTARUSP3PENTAMNT,NDIFUSP3PENTAMNT,NSTGUSP3CONTCNT,NTARUSP3CONTCNT,NDIFUSP3CONTCNT,NSTGURP5WTHDAMNT,NTARURP5WTHDAMNT,NDIFURP5WTHDAMNT,NSTGURP5FEEAMNT,NTARURP5FEEAMNT,NDIFURP5FEEAMNT,NSTGURP5PENTAMNT,NTARURP5PENTAMNT,NDIFURP5PENTAMNT,NSTGURP5CONTCNT,NTARURP5CONTCNT,NDIFURP5CONTCNT  FROM RC12A_TAR  ORDER BY SRNO");
		maps.put("RC122","SELECT VRTFND || ' (' || fnd.dmfundcd || ')' VRTFND,FROMDATE,TODATE,NSTGWTHDAMNT,NTARWTHDAMNT,NDIFWTHDAMNT,NSTGCONTCNT,NTARCONTCNT,NDIFCONTCNT  FROM RC12B_TAR rc, ZFUNDCD fnd WHERE trim(rc.vrtfnd) = trim(fnd.motfundcd)");
		maps.put("RC14","SELECT '',ACCNTYEAR,ACCNTMONTH,M_TCODE,BATCTRCDT,'',GLCODE,SACSCODE,SACSTYP,GLSIGN,INCHDRNUM,CHDRNUM,DSTRCH10ORGAMNT,DTARCH10ORGAMNT,DDIFCH10ORGAMNT,DSTRCH10SNGAMNT,DTARCH10SNGAMNT,DDIFCH10SNGAMNT,DSTRCH11ORGAMNT,DTARCH11ORGAMNT,DDIFCH11ORGAMNT,DSTRCH11SNGAMNT,DTARCH11SNGAMNT,DDIFCH11SNGAMNT,DSTRCH19ORGAMNT,DTARCH19ORGAMNT,DDIFCH19ORGAMNT,DSTRCH19SNGAMNT,DTARCH19SNGAMNT,DDIFCH19SNGAMNT,DSTRTOTLORGAMNT,DTARTOTLORGAMNT,DDIFTOTLORGAMNT,DSTRTOTLSNGAMNT,DTARTOTLSNGAMNT,DDIFTOTLSNGAMNT from RC14_TAR");
		maps.put("RC152","SELECT '',ACCNTYEAR,ACCNTMONTH,M_TCODE,BATCTRCDT,'',GLCODE,SACSCODE,SACSTYP,GLSIGN,INCHDRNUM,CHDRNUM,DSTRCH10ORGAMNT,DTARCH10ORGAMNT,DDIFCH10ORGAMNT,DSTRCH10SNGAMNT,DTARCH10SNGAMNT,DDIFCH10SNGAMNT,DSTRCH11ORGAMNT,DTARCH11ORGAMNT,DDIFCH11ORGAMNT,DSTRCH11SNGAMNT,DTARCH11SNGAMNT,DDIFCH11SNGAMNT,DSTRCH19ORGAMNT,DTARCH19ORGAMNT,DDIFCH19ORGAMNT,DSTRCH19SNGAMNT,DTARCH19SNGAMNT,DDIFCH19SNGAMNT,DSTRTOTLORGAMNT,DTARTOTLORGAMNT,DDIFTOTLORGAMNT,DSTRTOTLSNGAMNT,DTARTOTLSNGAMNT,DDIFTOTLSNGAMNT from RC15B_TAR");
		maps.put("RC16","SELECT SRNO,INCHDRNUM,CHDRNUM,SACSCODE,SACSTYP,DSTRSNGAMNT,DTARSNGAMNT,DDIFSNGAMNT from RC16_TAR order by srno");
		maps.put("RC17","SELECT '',chdr.REPNUM,fmc.CHDRNUM,fmc.LIFE,'USP3',fmc.ZFMCDAT,fmc.PCESDTE,fmc.SUMINS,fmc.MORTCLS   FROM ZFMCPF fmc, CHDRPF chdr WHERE fmc.CHDRNUM = chdr.CHDRNUM   AND chdr.validflag in ('1', '3') ORDER BY REPNUM");
		maps.put("RC18","SELECT CHDR.REPNUM,HITD.CHDRNUM,HITD.LIFE,HITD.COVERAGE,HITD.RIDER,HITD.ZINTBFND,HITD.EFFDATE,HITD.ZLSTINTDTE,HITD.ZNXTINTDTE,HITD.ZLSTFNDVAL,HITD.NAVPR FROM HITDPF HITD, CHDRPF CHDR WHERE HITD.CHDRNUM = CHDR.CHDRNUM AND CHDR.VALIDFLAG in ('1', '3') ORDER BY REPNUM");
		maps.put("RC19","SELECT chdr.REPNUM,covr.CHDRNUM,covr.LIFE,covr.CRTABLE,covr.COVERAGE,covr.RIDER,covr.BBLDAT FROM COVRPF covr, CHDRPF chdr WHERE covr.validflag = '1' AND chdr.validflag = '1'   AND covr.chdrnum = chdr.chdrnum ORDER BY REPNUM");
//		String key="RC11";
//		r.doReconcile(key+"_TAR.xlsx",key+"Recon.xlsx",maps.get(key),Integer.parseInt(key.substring(2)));
//		RC14Reconcile rc14=new RC14Reconcile();
//		String key="RC14";
//		rc14.doReconcile(key+"_TAR.xlsx",key+"Recon.xlsx",maps.get(key),Integer.parseInt(key.substring(2)));
		
		for(String key:maps.keySet()){
			System.out.println(key+":"+key.substring(2));
			r.doReconcile(key+"_TAR.xlsx",key+"Recon.xlsx",maps.get(key),Integer.parseInt(key.substring(2)));
		}
		System.out.println("Finsih");
	}
}
